# Generated by Django 2.2.11 on 2020-03-07 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200307_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 23, 23, 50, 888936)),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 23, 23, 50, 888936)),
        ),
    ]
