# Generated by Django 2.2.11 on 2020-03-07 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200307_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='gender_preferences',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('no matter', 'no matter')], default='no matter', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 23, 24, 15, 791859)),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 23, 24, 15, 791859)),
        ),
    ]
