# Generated by Django 2.2.11 on 2020-03-08 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200308_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 8, 15, 22, 42, 136919)),
        ),
        migrations.AlterField(
            model_name='order',
            name='room_url',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 8, 15, 22, 42, 136919)),
        ),
    ]
