# Generated by Django 2.2.11 on 2020-03-07 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 17, 26, 48, 573406)),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 7, 17, 26, 48, 573406)),
        ),
    ]
